# Name of your site (displayed in the header)
name: Janne Pelkonen

# Short bio or description (displayed in the header)
description: Developer 

# URL of your avatar or profile pic (you could use your GitHub profile pic)

